### ISSUE TITLE
Missing dist folder?

### ISSUE THREAD

**Issue by ahalma** [finnp/png-itxt#6]
Hi! 

I'd like to use this library in the browser. The docs state there is a "dist" folder with the browserified scripts. I can't find it anywhere though (nor a build script). Could you give me a pointer on how to continue?

Thanks! Arvid

**Comment by finnp** [comment]
Not sure what happened there, I think the browser section was added by another contributor. I'd suggest you should just try to use browerify yourself with this module. If you need to make changes to the code, I can add you ass a contributor as well.

**Comment by ahalma** [comment]
Thanks for you quick response. I'm not that familiar with those tools, so contributing to that part is out of my league I'm afraid...
